## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
controller:
  ingressClass: nginx-controller

  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

    internal:
      enabled: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      externalTrafficPolicy: Local

    enableHttp: true
    enableHttps: true
    targetPorts:
      http: 80
      https: special
    type: LoadBalancer

  containerPort:
    http: 80
    https: 443
    special: 8000

  extraVolumeMounts:
  ## Additional volumeMounts to the controller main container.
   - name: cache
     mountPath: /cache/nginx
   - name: mattermost-cache
     mountPath: /cache/mattermost

  extraVolumes:
  ## Additional volumes to the controller pod.
   - name: cache
     emptyDir: {}
   - name: mattermost-cache
     emptyDir: {}

  config:
    http-snippet: |
      proxy_cache_path /cache/nginx levels=1:2 keys_zone=mattermost_test_cache:10m max_size=10g inactive=120m use_temp_path=off;
      proxy_cache_path /cache/mattermost levels=1:2 keys_zone=mattermost_cache:10m max_size=10g inactive=120m use_temp_path=off;
    keep-alive: "3600"
    proxy-max-temp-file-size: "0"
    # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
    ssl-redirect: "false"
    force-ssl-redirect: "false"
    # remove the version of nginx from the responses
    server-tokens: "false"
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
         return 308 https://$host$request_uri;
      }

  resources:
   limits:
     cpu: "1"
     memory: 1Gi
   requests:
     cpu: 100m
     memory: 100Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 8
    targetCPUUtilizationPercentage: 400
    targetMemoryUtilizationPercentage: 400
  metrics:
     enabled: true

defaultBackend:
  enabled: true
  replicaCount: 2
